extends: default
rules:
  document-start:
    present: false
  truthy: disable
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 150
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    indent-sequences: consistent
